#!/usr/bin/env perl

use strict;
use warnings;

use JSON;
use Data::Dumper;
use Getopt::Long;
use LWP::UserAgent ;
use HTTP::Request::Common;

my $in_file 	= undef ;
my $out_file 	= undef ;
my $text 		= undef ;
my $verbose 	= 0 ;
my $debug   	= 0 ;



GetOptions ( 
	'input=s'	=> \$in_file,
	'output=s'  => \$out_file,
	'text=s'    => \$text,
	'verbose'   => \$verbose,
	'debug+'    => \$debug,
);


unless($in_file and -f $in_file){
	print STDERR "No input file provided.\nUsage:\t$0 -input FILE\n";
}

my $input ;

open(FILE , $in_file) or die "Can't open file $in_file for reading!\n" ;

while(my $line = <FILE>){
	$input .= $line ;
}

close(FILE) ;

my $json = JSON->new ;
my $biom = $json->decode($input);


my $header  = {} ;
my $keys    = {} ;
my $samples = {} ;

foreach my $col (@{$biom->{columns}}){
	
	foreach my $key (keys %{$col->{metadata}}){	
		#print $key , "\n" ;
	
		next if ($key =~/project/);
		
		foreach my $tag (keys %{$col->{metadata}->{$key}}){
			
			$col->{metadata}->{$key . "." . $tag} = $col->{metadata}->{$key}->{$tag} ;
		
			
			if (ref  $col->{metadata}->{$key}->{$tag} ){
				
				foreach my $tmp (keys %{$col->{metadata}->{$key}->{$tag}}){
					
					next if (ref $col->{metadata}->{$key}->{$tag}->{$tmp});
					
					my $value = ( $col->{metadata}->{$key}->{$tag}->{$tmp} || "0" );
					$value =~s/\n// ;
					$samples->{ $col->{id} }->{ $key . "." . $tag . "." . $tmp } = $value;
					$keys->{ $key . "." . $tag . "." . $tmp }++
				}
				
			}
			else{
				$samples->{ $col->{id} }->{ $key . "." . $tag } = $col->{metadata}->{$key}->{$tag} ;
				$keys->{ $key . "." . $tag }++ ;
			}
		}
		delete $col->{metadata}->{$key}
		
	}
}

#print Dumper $biom ;

print join("\t" , "#SampleID" , keys %$keys) , "\n";
foreach my $sample (keys %$samples) {
	
	
	print $sample ;
	foreach my $key  (keys %$keys){
		print "\t" , ( $samples->{$sample}->{$key} ? "\"" . $samples->{$sample}->{$key} . "\"" : '"0"' ) ;
	}
	print "\n" ;
}


#print $json->encode($biom)